### ISSUE TITLE
Nwot wwittenw inw wust

### ISSUE THREAD

**Issue by Leastrio** [shadowninja55/carbon#1]
A bwig issue with ᴄawbwonw is that it is nwot wwittenw inw wust~
Ifw we wewwite it inw wust that wiww mwakwe it a wot fwastew anwⅾ mwemwowi safwe~

**Comment by Flinner** [comment]
demu hasekeww safe desu >w<

**Comment by Leastrio** [comment]
Haskeww iws witewawwy swowew than python, i bewieve cawbon shouwd be a fawst wanguage awnd thewefowe shouwd be wwitten in wust~

**Comment by shadowninja55** [comment]
not being written in rust is an intentional design feature, and it's one of carbon's most redeeming qualities!
